# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
#load codacy orb
orbs:
  coverage-reporter: codacy/coverage-reporter@10.0.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:4.2.2
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - react-app/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test-api-unit
      - run: yarn test-api-integration
      - run: yarn test-react-app
  codacy-coverage-report:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - react-app/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test-coverage
      - coverage-reporter/send_report:
          coverage-reports: 'report.xml,coverage.info'
          project-token: $CODACY_PROJECT_TOKEN